In [2]:
import numpy as np
arr=np.arange(20)
arr1=np.arange(20,50)
arr_slice= slice(3,15,2)
print(arr[arr_slice], arr1[arr_slice])

[ 3  5  7  9 11 13] [23 25 27 29 31 33]


In [7]:
arr= np.array([1,2,3])
arr_2d=np.array([[11,12,13],[21,22,23]])
print('1-D array:')
print(arr)
print('2-D array:')
print(arr_2d)
print('Shape:')
print(arr.shape, arr_2d.shape)

1-D array:
[1 2 3]
2-D array:
[[11 12 13]
 [21 22 23]]
Shape:
(3,) (2, 3)


In [8]:
arr[2]=85
print(arr)

[ 1  2 85]


In [21]:
zeros= np.zeros((2,4,8))   #(number of times, row, column)
print(zeros)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


In [3]:
full=np.full((2,3),(8.2))
print(full)

[[8.2 8.2 8.2]
 [8.2 8.2 8.2]]


In [36]:
eye=np.eye(4,4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
res=full.reshape(3,2)
print(res)
flat=res.flatten()
print(flat)

[[8.2 8.2]
 [8.2 8.2]
 [8.2 8.2]]
[8.2 8.2 8.2 8.2 8.2 8.2]


In [16]:
import pandas as pd
sr= pd.Series([12,22,34,9], ['a','b','c','d'])
print(sr)

df= pd.DataFrame([12,45,56,32], index=['a','b','x','y'],dtype=float)
print(df)

a    12
b    22
c    34
d     9
dtype: int64
      0
a  12.0
b  45.0
x  56.0
y  32.0


In [25]:
import numpy as np
arr=np.array([[12,23,23],[89,78,76]])
print(arr)
print('--------')
df2=pd.DataFrame(arr,index=['Ankita','Ayush'])
print(df2)
print('--------')

df3={'Bingo':pd.Series([12,13,14],index=['a','b','c']),
    'uno': pd.Series([34,23,21],index=['a','b','c'])}
print(pd.DataFrame(df3))

[[12 23 23]
 [89 78 76]]
--------
         0   1   2
Ankita  12  23  23
Ayush   89  78  76
--------
   Bingo  uno
a     12   34
b     13   23
c     14   21


In [3]:
import numpy as np
import pandas as pd
df1={'A': [1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
df=pd.DataFrame(df1)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [4]:
df['State']='CA AZ VA'.split()
df

A    B  C State
0  1.0  5.0  1    CA
1  2.0  NaN  2    AZ
2  NaN  NaN  3    VA

In [7]:
df.set_index('State',inplace = True)
df

A    B  C
State             
CA     1.0  5.0  1
AZ     2.0  NaN  2
VA     NaN  NaN  3

In [ ]:
df.dropna(axis=0,how='any')

In [1]:
import numpy as np
a=np.ones((4,4))
print("Keeping only inner square as 0")
a[1:-1,1:-1] = 0
a

Keeping only inner square as 0


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [5]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [7]:
a=np.arange(0,27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
a= np.array([[10,11,12],[20,21,22],[30,31,32]])
print(a)
print('Sum of rows = ', np.sum(a, axis=1))
print('Sum of columns= ',np.sum(a,axis=0))
print("Sum of all elements=",np.sum(a))

[[10 11 12]
 [20 21 22]
 [30 31 32]]
Sum of rows =  [33 63 93]
Sum of columns=  [60 63 66]
Sum of all elements= 189


In [17]:
'''Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]    '''
v= np.array([1,1,0])
m= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('After adding the vector v to each row of the matrix m:')
for i in range(0,4):
    print(m[i,:]+v)

After adding the vector v to each row of the matrix m:
[2 3 3]
[5 6 6]
[8 9 9]
[11 12 12]


In [21]:
'''Write a NumPy program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]'''
a=np.zeros(10)
a[7]=11
a

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.])